export const ZONE_DISTRICTS: Record<string, string[]> = {
  "All": ["All"],
  "Ajmer": ["Ajmer", "Beawer", "Bhilwara", "Nagaur", "Tonk"],
  "Bikaner": ["Bikaner", "Churu", "Ganganar", "Hanumangarh"],
  "Jodhpur": ["Barmer", "Balotra", "Jaisalmer", "Jalore", "Jodhpur", "Pali", "Phalodi", "Sirohi"],
  "Udaipur": ["Banswara", "Chittorgarh", "Dungarpur", "Rajsamand", "Pratapgarh", "Udaipur"]
};

export const ROLES = [
  "Engineer",
  "Manager",
  "Division Manager",
  "Coordinator",
  "Accountant",
  "HR",
  "Project Head",
  "Travel Tesk",
  "MIS",
  "VP",
  "Admin"
];

export const DESIGNATIONS = [
  "Accountant",
  "Accounts Manager",
  "Admin Assistant",
  "Administration and IT-Manager",
  "Analysist-Marketing",
  "Application Specialist",
  "Area Sales Manager",
  "Area Service Manager",
  "Assistant General Manager-Operation Service",
  "Assistant Manager",
  "Assistant Manager (Accounts)",
  "Assistant Manager (procurement)",
  "Associate VP-Sales",
  "Biomedical Engineer",
  "Biomedical Lead Engineer",
  "Biomedical Technician",
  "Branch HR Officer",
  "Branch Head",
  "Branch Officer",
  "Business Manager",
  "Calibration Engineer",
  "Calibration Service Engineer",
  "Chief Marketing Officer",
  "Chief Technical Officer",
  "Consultant-TA",
  "Coordinator-RND",
  "Coordinator-Service Sales",
  "Customer Care Executive-Marketing",
  "Data Operator-Marketing",
  "Deputy Manager-Purchase",
  "Deputy Manager-Procurment",
  "Deputy Manager-South Zone (TCQA)",
  "Digital Marketing Specialist",
  "Director",
  "District In-charge",
  "District Lead-Engineer",
  "Divisional Manager",
  "Driver",
  "Dy Manager-TCQA(North Zone)",
  "Dy. Manager (Service)",
  "Executive - Accounts",
  "Executive Director",
  "Executive-QA",
  "Executive-Warehouse",
  "GM sales",
  "Genaral Manager-Finance",
  "General Manager-Govt Business",
  "HR Executive",
  "HR Executive-TA",
  "HRBP-Service",
  "IT head",
  "Incharge Logistics and Warehouse",
  "Jr Executive-Warehouse",
  "Jr. Accountant",
  "Jr. Executive (procurement)",
  "Jr. HR Executive",
  "Jr. Office Coordinator",
  "Jr. Purchase Executive",
  "Jr. Specialist Engineer (Lab)",
  "Jr. Specialist Engineer (Radiology)",
  "Jr. Specialist Engineer-Chip level",
  "Jr. office coordinator-DnD",
  "Jr.Application Specialist",
  "Jr.Biomedical Engineer",
  "Jr.Calibration Engineer",
  "Jr.Sales Engineer",
  "Jr.Sales Engineer-Calibration",
  "Jr.Service Coordinator",
  "Jr.Service Engineer",
  "Jr.Service Engineer-Calibration",
  "Jr.Specialist Engineer",
  "Jr.Store Assistant",
  "Junior Auditor",
  "Junior Tutor",
  "Lead Engineer",
  "Lead Faculty-Accademic",
  "Lead Sales Coordinator",
  "Lead Sales Engineer",
  "Lead Service Engineer",
  "Line of Business InCharge",
  "MIS Executive",
  "MIS Executive-HR",
  "Manager (Radiology Products)",
  "Manager- Tech Support Operation",
  "Manager-HR",
  "Manager-Quality and Field Audit",
  "Manager-Service",
  "Office Assistant",
  "Office Coordinator",
  "Office Coordinator-DnD",
  "Product Sales Manager(Ciyan)",
  "Project Head",
  "Project Technical Manager",
  "Purchase Assistant",
  "Purchase Executive",
  "QA Engineer",
  "Regional Manger-Govt Business",
  "Regional Sales Manager",
  "Regional Technical Lead",
  "Sales Coordinator",
  "Sales Engineer",
  "Sales Executive",
  "Senior Coordinator-Operation",
  "Senior Deputy Manager-Procurement",
  "Senior Executive IT",
  "Senior Executive- MIS",
  "Senior Manager-Warehouse",
  "Senior Project Coordinator",
  "Senior Sevice Coordinator-DND",
  "Senior Specialist Engineer (BBR)",
  "Service Coordinator",
  "Service Coordinator-Field",
  "Service Engineer",
  "Service Engineer-Calibration",
  "Service Engineer-Fuji",
  "Service Manager",
  "Specialist Engineer",
  "Specialist Engineer (BBR)",
  "Specialist Engineer (CR)",
  "Specialist Engineer (Chip Level)",
  "Specialist Engineer (Dental)",
  "Specialist Engineer (Dialysis)",
  "Specialist Engineer (Lab)",
  "Specialist Engineer (PSA)",
  "Specialist Engineer (R O Plant)",
  "Specialist Engineer (Radiology)",
  "Specialist Engineer (Ultrasound)",
  "Specialist Engineer(Xray)",
  "Specialist Engineer-Critical",
  "Sr. Accountant",
  "Sr. Biomedical Engineer",
  "Sr. Engineer-Quality Assurance",
  "Sr. Executive (Data and Documentation)",
  "Sr. Executive-Sales and Marketing",
  "Sr. HR Executive",
  "Sr. Manager (TRC)",
  "Sr. Office Coordinator",
  "Sr. Procurement Executive",
  "Sr. Project Survery Analyst",
  "Sr. Sales Coordinator",
  "Sr. Sales Engineer",
  "Sr. Service Coordinator",
  "Sr. Specialist Engineer (Lab)",
  "Sr. Specialist Engineer (PSA)",
  "Sr. Specialist Engineer (TRC)",
  "Sr. Specialist Engineer-Dialysis",
  "Sr. Specialist Engineer-X-Ray",
  "Sr.Calibration Engineer",
  "Sr.Service Engineer",
  "Sr.Service Engineer Calibration",
  "Sr.Specialist Engineer",
  "Sr.Specialist Engineer-CR",
  "Sr.Specialist Engineer-Chip Level",
  "Store Assistant",
  "Store Cum Office Boy",
  "Support Engineer",
  "Support Engineer-Calibration",
  "Support Engineer-TRC",
  "System Engineer",
  "Technical Facilitator",
  "Technician",
  "Territory Business Manager",
  "Territory Service Sales Manager",
  "Trainee Field Engineer",
  "Trainee Office Coordinator",
  "Trainee Purchase Assistant",
  "Trainee Technician",
  "Trainee-Service Coordinator",
  "Trainer",
  "Vice President BEMP",
  "Warehouse Executive",
  "Warehouse Officer",
  "Zonal Manager"
];
